spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernateint?currentSchema=hibentities
    username: hibtest
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
